# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu on Microsoft Azure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Run the mdl linting tool
        # Refers to .mdlrc file in repository
        - name: Run Markdown Linting
          uses: actionshub/markdownlint@main
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
        # Install pipenv
        - name: Install Pipenv
          if: always()
          run: |
            pip install pipenv
        # Run the Python program
        - name: Run Python Program
          if: always()
          run: |
            cd source
            python demonstrate-variable-limitations.py
            python compare-variables.py
        # Determine the version of Gradle
        - name: Determine Gradle Version
          if: always()
          run: |
            gradle --version
        # Run GatorGrader: see config/gatorgrade.yml
        - name: Run GatorGrader with GatorGrade
          if: always()
          run:  |
            pip install gatorgrade
            gatorgrade --config config/gatorgrade.yml
